package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.DatosGenerales;
import modelo.ProductDAO;
import modelo.Products;
import modelo.Provider;
import modelo.ProviderDAO;
import modelo.UsuarioDAO;

public class FrmComprobanteCompra extends javax.swing.JFrame {

    Products prod = new Products();
    ProductDAO prodDAO = new ProductDAO();

    DatosGenerales datos = new DatosGenerales();
    UsuarioDAO usDAO = new UsuarioDAO();

    Provider prov = new Provider();
    ProviderDAO provDAO = new ProviderDAO();

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form frmReporte
     */
    public FrmComprobanteCompra(int codigo) {
        initComponents();
        lblNUMEROCOMPROBANTE.setText("" + codigo);
        listarDetalle(codigo);
        calcularCompra();
        datos = usDAO.getConfig();
        lblNRUC_EMPRESA.setText(datos.getRuc());
        lblNOMBRE_EMPRESA.setText(datos.getNombre());
        prov = provDAO.getData(codigo);
        lblNOMBRE_PROVEEDOR.setText(prov.getName_provider());
        lblTELEFONO_PROVEEDOR.setText(prov.getPhone_provider());
        lblDIRECCION_PROVEEDOR.setText(prov.getAddress_provider());

    }


    public void listarDetalle(int codigo) {
        List<Products> lista = prodDAO.ListaDetalle(codigo);
        modelo = (DefaultTableModel) tableCOMPROBANTE.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getQuantity();
            ob[1] = lista.get(i).getDescription_product();
            ob[2] = lista.get(i).getPurchase_price();
            ob[3] = lista.get(i).getSale_price();
            modelo.addRow(ob);
        }
        tableCOMPROBANTE.setModel(modelo);
        JTableHeader header = tableCOMPROBANTE.getTableHeader();
        header.setOpaque(false);
        header.setBackground(Color.yellow);
        header.setForeground(Color.black);
    }

    private void calcularCompra() {
        double total = 0.00;
        int numFila = tableCOMPROBANTE.getRowCount();
        for (int i = 0; i < numFila; i++) {
            total = total + Double.parseDouble(String.valueOf(tableCOMPROBANTE.getValueAt(i, 3)));
        }
        lblTOTAL_COMPROBANTE.setText("" + total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCOMPROBANTE = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCOMPROBANTE = new javax.swing.JTable();
        lblNOMBRE_EMPRESA = new javax.swing.JLabel();
        lblTOTAL_COMPROBANTE = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNUMEROCOMPROBANTE = new javax.swing.JLabel();
        lblNRUC_EMPRESA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTELEFONO = new javax.swing.JLabel();
        lblNOMBRE_PROVEEDOR = new javax.swing.JLabel();
        lblDIRECCION_PROVEEDOR = new javax.swing.JLabel();
        lblTELEFONO_PROVEEDOR = new javax.swing.JLabel();
        btnIMPRIMIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCOMPROBANTE.setBackground(new java.awt.Color(255, 255, 255));
        panelCOMPROBANTE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCOMPROBANTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant.", "Decripción", "Precio", "SubTotal"
            }
        ));
        tableCOMPROBANTE.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableCOMPROBANTE);
        if (tableCOMPROBANTE.getColumnModel().getColumnCount() > 0) {
            tableCOMPROBANTE.getColumnModel().getColumn(0).setPreferredWidth(1);
            tableCOMPROBANTE.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableCOMPROBANTE.getColumnModel().getColumn(2).setPreferredWidth(20);
            tableCOMPROBANTE.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        panelCOMPROBANTE.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 520, 340));

        lblNOMBRE_EMPRESA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNOMBRE_EMPRESA.setText("Nombre");
        panelCOMPROBANTE.add(lblNOMBRE_EMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblTOTAL_COMPROBANTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTOTAL_COMPROBANTE.setText("-----");
        panelCOMPROBANTE.add(lblTOTAL_COMPROBANTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("NOMBRE:");
        panelCOMPROBANTE.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("SERVICES RAPID EIRL");
        jLabel4.setToolTipText("");
        panelCOMPROBANTE.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NÚMERO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("RUC:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 80, 40));

        lblNUMEROCOMPROBANTE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNUMEROCOMPROBANTE.setText("1");
        jPanel2.add(lblNUMEROCOMPROBANTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 20, -1));

        lblNRUC_EMPRESA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNRUC_EMPRESA.setForeground(new java.awt.Color(255, 0, 0));
        lblNRUC_EMPRESA.setText("001");
        jPanel2.add(lblNRUC_EMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 4, 130, 40));

        panelCOMPROBANTE.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 220, 120));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("DIRECCIÓN:");
        panelCOMPROBANTE.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("TOTAL:");
        panelCOMPROBANTE.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("Datos Generales: PROVEEDOR");
        panelCOMPROBANTE.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblTELEFONO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTELEFONO.setForeground(new java.awt.Color(51, 51, 255));
        lblTELEFONO.setText("Telefono");
        panelCOMPROBANTE.add(lblTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        lblNOMBRE_PROVEEDOR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNOMBRE_PROVEEDOR.setText("Nombre Proveedor");
        panelCOMPROBANTE.add(lblNOMBRE_PROVEEDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblDIRECCION_PROVEEDOR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDIRECCION_PROVEEDOR.setText("Dirección proveedor");
        panelCOMPROBANTE.add(lblDIRECCION_PROVEEDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblTELEFONO_PROVEEDOR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTELEFONO_PROVEEDOR.setText("Número");
        panelCOMPROBANTE.add(lblTELEFONO_PROVEEDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        getContentPane().add(panelCOMPROBANTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 570, 630));

        btnIMPRIMIR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIMPRIMIR.setText("IMPRIMIR");
        btnIMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIMPRIMIRActionPerformed(evt);
            }
        });
        getContentPane().add(btnIMPRIMIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIMPRIMIRActionPerformed
        Toolkit imprimir = panelCOMPROBANTE.getToolkit();
        PrintJob imprimirTrabajo = imprimir.getPrintJob(this, null, null);
        Graphics graf = imprimirTrabajo.getGraphics();
        panelCOMPROBANTE.print(graf);
        graf.dispose();
        imprimirTrabajo.end();
    }//GEN-LAST:event_btnIMPRIMIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIMPRIMIR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblDIRECCION_PROVEEDOR;
    public javax.swing.JLabel lblNOMBRE_EMPRESA;
    public javax.swing.JLabel lblNOMBRE_PROVEEDOR;
    public javax.swing.JLabel lblNRUC_EMPRESA;
    private javax.swing.JLabel lblNUMEROCOMPROBANTE;
    public javax.swing.JLabel lblTELEFONO;
    public javax.swing.JLabel lblTELEFONO_PROVEEDOR;
    private javax.swing.JLabel lblTOTAL_COMPROBANTE;
    private javax.swing.JPanel panelCOMPROBANTE;
    public javax.swing.JTable tableCOMPROBANTE;
    // End of variables declaration//GEN-END:variables
}
