/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SlidingController;

/**
 *
 * @author Natsu98fx
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        SlidingController slide = new SlidingController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new RSMaterialComponent.RSPanelMaterial();
        btnHome = new rojerusan.RSButtonIconI();
        btnCompras = new rojerusan.RSButtonIconI();
        btnVentas = new rojerusan.RSButtonIconI();
        btnProductos = new rojerusan.RSButtonIconI();
        btnClientes = new rojerusan.RSButtonIconI();
        btnProveedor = new rojerusan.RSButtonIconI();
        btnCategorias = new rojerusan.RSButtonIconI();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        btnUsuarios = new rojerusan.RSButtonIconI();
        btnSalir = new rojerusan.RSButtonIconI();
        btnReportes = new rojerusan.RSButtonIconI();
        pnlTopBar = new RSMaterialComponent.RSPanelMaterial();
        rSLabelSombra1 = new rojeru_san.rslabel.RSLabelSombra();
        rSLabelImage1 = new rojeru_san.rslabel.RSLabelImage();
        btnCerrar = new RSMaterialComponent.RSButtonIconOne();
        pnlPrincipal = new RSMaterialComponent.RSPanelMaterial();
        pnlSlider = new newscomponents.RSPanelEffect();
        pnlHome = new vista.VistaHome();
        pnlVentas = new vista.VistaVentas();
        pnlProductos = new vista.VistaProductos();
        pnlClientes = new vista.VistaClientes();
        pnlCategorias = new vista.VistaCategorias();
        pnlProveedores = new vista.VistaProveedores();
        pnlUsuarios = new vista.VistaUsuarios();
        pnlReportes = new vista.VistaReportes();
        pnlPrueba = new vista.TabMarcas();
        pnlCompras = new vista.VistaCompras();
        vistaCompras1 = new vista.VistaCompras();
        vistaProductos1 = new vista.VistaProductos();
        vistaClientes1 = new vista.VistaClientes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setIntensity(5);
        pnlMenu.setShadowBottom(false);
        pnlMenu.setShadowLeft(false);
        pnlMenu.setShadowTop(false);

        btnHome.setBackground(new java.awt.Color(102, 102, 102));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setColorHover(new java.awt.Color(51, 51, 51));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setSelected(true);

        btnCompras.setBackground(new java.awt.Color(102, 102, 102));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-sale.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setColorHover(new java.awt.Color(51, 51, 51));
        btnCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnVentas.setBackground(new java.awt.Color(102, 102, 102));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-venta.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setColorHover(new java.awt.Color(51, 51, 51));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnProductos.setBackground(new java.awt.Color(102, 102, 102));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-product.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setColorHover(new java.awt.Color(51, 51, 51));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnClientes.setBackground(new java.awt.Color(102, 102, 102));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cliente.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setColorHover(new java.awt.Color(51, 51, 51));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnProveedor.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedor.setText("Proveedor");
        btnProveedor.setColorHover(new java.awt.Color(51, 51, 51));
        btnProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCategorias.setBackground(new java.awt.Color(102, 102, 102));
        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-roles.png"))); // NOI18N
        btnCategorias.setText("Categorías");
        btnCategorias.setColorHover(new java.awt.Color(51, 51, 51));
        btnCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rSPanelMaterialImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/autopartes-logo.png"))); // NOI18N
        rSPanelMaterialImage1.setShadowBottom(false);
        rSPanelMaterialImage1.setShadowLeft(false);
        rSPanelMaterialImage1.setShadowRight(false);
        rSPanelMaterialImage1.setShadowTop(false);

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        btnUsuarios.setBackground(new java.awt.Color(102, 102, 102));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-user.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setColorHover(new java.awt.Color(51, 51, 51));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setColorHover(new java.awt.Color(51, 51, 51));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnReportes.setBackground(new java.awt.Color(102, 102, 102));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-roles.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setColorHover(new java.awt.Color(51, 51, 51));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 260, 710));

        pnlTopBar.setShadowBottom(false);
        pnlTopBar.setShadowLeft(false);
        pnlTopBar.setShadowRight(false);
        pnlTopBar.setShadowTop(false);

        rSLabelSombra1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelSombra1.setText("Sistema de Ventas de Autopartes");
        rSLabelSombra1.setColorDeSombra(new java.awt.Color(37, 45, 223));
        rSLabelSombra1.setFont(new java.awt.Font("Roboto Cn", 1, 36)); // NOI18N

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-sistema.png"))); // NOI18N

        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopBarLayout = new javax.swing.GroupLayout(pnlTopBar);
        pnlTopBar.setLayout(pnlTopBarLayout);
        pnlTopBarLayout.setHorizontalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSLabelSombra1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 631, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlTopBarLayout.setVerticalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSLabelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rSLabelSombra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(pnlTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1281, -1));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setIntensity(5);
        pnlPrincipal.setRound(10);

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));

        pnlHome.setName("pnlHome"); // NOI18N
        pnlSlider.add(pnlHome, "card10");

        pnlVentas.setName("pnlVentas"); // NOI18N
        pnlSlider.add(pnlVentas, "card5");

        pnlProductos.setName("pnlProductos"); // NOI18N
        pnlSlider.add(pnlProductos, "card6");

        pnlClientes.setName("pnlClientes"); // NOI18N
        pnlSlider.add(pnlClientes, "card9");

        pnlCategorias.setName("pnlCategorias"); // NOI18N
        pnlSlider.add(pnlCategorias, "card7");

        pnlProveedores.setName("pnlProveedores"); // NOI18N
        pnlSlider.add(pnlProveedores, "card3");

        pnlUsuarios.setName("pnlUsuarios"); // NOI18N
        pnlSlider.add(pnlUsuarios, "card4");
        pnlSlider.add(pnlReportes, "card10");
        pnlSlider.add(pnlPrueba, "card11");
        pnlSlider.add(pnlCompras, "card12");
        pnlSlider.add(vistaCompras1, "card12");
        pnlSlider.add(vistaProductos1, "card13");
        pnlSlider.add(vistaClientes1, "card14");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        System.out.println("soy un pto error >:V");

        jPanel1.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 1000, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        /*System.exit(0);*/
        VistaWarningSalir salir = new VistaWarningSalir();
        salir.titulo.setText("¿ESTAS SEGURO DE SALIR?");
        salir.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojerusan.RSButtonIconI btnCategorias;
    private RSMaterialComponent.RSButtonIconOne btnCerrar;
    public rojerusan.RSButtonIconI btnClientes;
    public rojerusan.RSButtonIconI btnCompras;
    public rojerusan.RSButtonIconI btnHome;
    public rojerusan.RSButtonIconI btnProductos;
    public rojerusan.RSButtonIconI btnProveedor;
    public rojerusan.RSButtonIconI btnReportes;
    public rojerusan.RSButtonIconI btnSalir;
    public rojerusan.RSButtonIconI btnUsuarios;
    public rojerusan.RSButtonIconI btnVentas;
    private javax.swing.JPanel jPanel1;
    public vista.VistaCategorias pnlCategorias;
    public vista.VistaClientes pnlClientes;
    public vista.VistaCompras pnlCompras;
    public vista.VistaHome pnlHome;
    private RSMaterialComponent.RSPanelMaterial pnlMenu;
    public RSMaterialComponent.RSPanelMaterial pnlPrincipal;
    public vista.VistaProductos pnlProductos;
    public vista.VistaProveedores pnlProveedores;
    public vista.TabMarcas pnlPrueba;
    public vista.VistaReportes pnlReportes;
    public newscomponents.RSPanelEffect pnlSlider;
    private RSMaterialComponent.RSPanelMaterial pnlTopBar;
    public vista.VistaUsuarios pnlUsuarios;
    public vista.VistaVentas pnlVentas;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage1;
    private rojeru_san.rslabel.RSLabelSombra rSLabelSombra1;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    private vista.VistaClientes vistaClientes1;
    private vista.VistaCompras vistaCompras1;
    private vista.VistaProductos vistaProductos1;
    // End of variables declaration//GEN-END:variables
}
