/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SlidingController;

/**
 *
 * @author Natsu98fx
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaUsuarios2 = new vista.VistaUsuarios();
        jPanel1 = new javax.swing.JPanel();
        pnlTopBar = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        btnSalir = new rojerusan.RSButtonIconI();
        btnHome = new rojerusan.RSButtonIconI();
        btnReportes = new rojerusan.RSButtonIconI();
        btnCategorias = new rojerusan.RSButtonIconI();
        btnUsuarios = new rojerusan.RSButtonIconI();
        btnProveedores = new rojerusan.RSButtonIconI();
        btnClientes = new rojerusan.RSButtonIconI();
        btnProductos = new rojerusan.RSButtonIconI();
        btnVentas = new rojerusan.RSButtonIconI();
        btnCompras = new rojerusan.RSButtonIconI();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();
        pnlSlider = new rojeru_san.rspanel.RSPanelEffect();
        pnlHome = new vista.VistaHome();
        pnlCompras = new vista.VistaCompras();
        pnlVentas = new vista.VistaVentas();
        pnlProductos = new vista.VistaProductos();
        pnlClientes = new vista.VistaClientes();
        pnlProveedores = new vista.VistaProveedores();
        pnlUsuarios = new vista.VistaUsuarios();
        pnlCategorias = new vista.VistaCategorias();
        pnlReportes = new vista.VistaReportes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlTopBar.setShadowLeft(false);
        pnlTopBar.setShadowRight(false);
        pnlTopBar.setShadowTop(false);

        javax.swing.GroupLayout pnlTopBarLayout = new javax.swing.GroupLayout(pnlTopBar);
        pnlTopBar.setLayout(pnlTopBarLayout);
        pnlTopBarLayout.setHorizontalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pnlTopBarLayout.setVerticalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setShadowBottom(false);
        rSPanelMaterial1.setShadowLeft(false);
        rSPanelMaterial1.setShadowTop(false);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterialImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/autopartes-logo.png"))); // NOI18N
        rSPanelMaterialImage1.setShadowBottom(false);
        rSPanelMaterialImage1.setShadowLeft(false);
        rSPanelMaterialImage1.setShadowRight(false);
        rSPanelMaterialImage1.setShadowTop(false);

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        rSPanelMaterial1.add(rSPanelMaterialImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.setColorHover(new java.awt.Color(51, 51, 51));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setMaximumSize(new java.awt.Dimension(182, 33));
        btnSalir.setMinimumSize(new java.awt.Dimension(182, 33));
        btnSalir.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 240, -1));

        btnHome.setBackground(new java.awt.Color(102, 102, 102));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setToolTipText("");
        btnHome.setColorHover(new java.awt.Color(51, 51, 51));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setMaximumSize(new java.awt.Dimension(182, 33));
        btnHome.setMinimumSize(new java.awt.Dimension(182, 33));
        btnHome.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, -1));

        btnReportes.setBackground(new java.awt.Color(102, 102, 102));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("");
        btnReportes.setColorHover(new java.awt.Color(51, 51, 51));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReportes.setMaximumSize(new java.awt.Dimension(182, 33));
        btnReportes.setMinimumSize(new java.awt.Dimension(182, 33));
        btnReportes.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 240, -1));

        btnCategorias.setBackground(new java.awt.Color(102, 102, 102));
        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnCategorias.setText("Categorías");
        btnCategorias.setToolTipText("");
        btnCategorias.setColorHover(new java.awt.Color(51, 51, 51));
        btnCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCategorias.setMaximumSize(new java.awt.Dimension(182, 33));
        btnCategorias.setMinimumSize(new java.awt.Dimension(182, 33));
        btnCategorias.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, -1));

        btnUsuarios.setBackground(new java.awt.Color(102, 102, 102));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setToolTipText("");
        btnUsuarios.setColorHover(new java.awt.Color(51, 51, 51));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setMaximumSize(new java.awt.Dimension(182, 33));
        btnUsuarios.setMinimumSize(new java.awt.Dimension(182, 33));
        btnUsuarios.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 240, -1));

        btnProveedores.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setToolTipText("");
        btnProveedores.setColorHover(new java.awt.Color(51, 51, 51));
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProveedores.setMaximumSize(new java.awt.Dimension(182, 33));
        btnProveedores.setMinimumSize(new java.awt.Dimension(182, 33));
        btnProveedores.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, -1));

        btnClientes.setBackground(new java.awt.Color(102, 102, 102));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setToolTipText("");
        btnClientes.setColorHover(new java.awt.Color(51, 51, 51));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes.setMaximumSize(new java.awt.Dimension(182, 33));
        btnClientes.setMinimumSize(new java.awt.Dimension(182, 33));
        btnClientes.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, -1));

        btnProductos.setBackground(new java.awt.Color(102, 102, 102));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setToolTipText("");
        btnProductos.setColorHover(new java.awt.Color(51, 51, 51));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProductos.setMaximumSize(new java.awt.Dimension(182, 33));
        btnProductos.setMinimumSize(new java.awt.Dimension(182, 33));
        btnProductos.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, -1));

        btnVentas.setBackground(new java.awt.Color(102, 102, 102));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setToolTipText("");
        btnVentas.setColorHover(new java.awt.Color(51, 51, 51));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVentas.setMaximumSize(new java.awt.Dimension(182, 33));
        btnVentas.setMinimumSize(new java.awt.Dimension(182, 33));
        btnVentas.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        btnCompras.setBackground(new java.awt.Color(102, 102, 102));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-home.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setToolTipText("");
        btnCompras.setColorHover(new java.awt.Color(51, 51, 51));
        btnCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCompras.setMaximumSize(new java.awt.Dimension(182, 33));
        btnCompras.setMinimumSize(new java.awt.Dimension(182, 33));
        btnCompras.setPreferredSize(new java.awt.Dimension(250, 40));
        rSPanelMaterial1.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, -1));

        rSPanelMaterial2.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial2.setIntensity(5);
        rSPanelMaterial2.setRound(10);

        pnlSlider.add(pnlHome, "card7");
        pnlSlider.add(pnlCompras, "card8");
        pnlSlider.add(pnlVentas, "card9");
        pnlSlider.add(pnlProductos, "card6");
        pnlSlider.add(pnlClientes, "card10");
        pnlSlider.add(pnlProveedores, "card2");
        pnlSlider.add(pnlUsuarios, "card5");
        pnlSlider.add(pnlCategorias, "card4");
        pnlSlider.add(pnlReportes, "card3");

        javax.swing.GroupLayout rSPanelMaterial2Layout = new javax.swing.GroupLayout(rSPanelMaterial2);
        rSPanelMaterial2.setLayout(rSPanelMaterial2Layout);
        rSPanelMaterial2Layout.setHorizontalGroup(
            rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        rSPanelMaterial2Layout.setVerticalGroup(
            rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojerusan.RSButtonIconI btnCategorias;
    public rojerusan.RSButtonIconI btnClientes;
    public rojerusan.RSButtonIconI btnCompras;
    public rojerusan.RSButtonIconI btnHome;
    public rojerusan.RSButtonIconI btnProductos;
    public rojerusan.RSButtonIconI btnProveedores;
    public rojerusan.RSButtonIconI btnReportes;
    public rojerusan.RSButtonIconI btnSalir;
    public rojerusan.RSButtonIconI btnUsuarios;
    public rojerusan.RSButtonIconI btnVentas;
    private javax.swing.JPanel jPanel1;
    public vista.VistaCategorias pnlCategorias;
    public vista.VistaClientes pnlClientes;
    public vista.VistaCompras pnlCompras;
    public vista.VistaHome pnlHome;
    public vista.VistaProductos pnlProductos;
    public vista.VistaProveedores pnlProveedores;
    public vista.VistaReportes pnlReportes;
    public rojeru_san.rspanel.RSPanelEffect pnlSlider;
    private RSMaterialComponent.RSPanelMaterial pnlTopBar;
    public vista.VistaUsuarios pnlUsuarios;
    public vista.VistaVentas pnlVentas;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    private vista.VistaUsuarios vistaUsuarios2;
    // End of variables declaration//GEN-END:variables
}
