/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

    public class VistaVentas extends javax.swing.JPanel{

    /**
     * Creates new form VistaVentas
     */
    public VistaVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelMaterialGradient1 = new RSMaterialComponent.RSPanelMaterialGradient();
        jLabel1 = new javax.swing.JLabel();
        pnlSlider = new newscomponents.RSPanelEffect();
        txtSearchUser = new RSMaterialComponent.RSTextFieldIconOne();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new rojerusan.RSTableMetro();
        btnNewUser = new newscomponents.RSButtonGradientIcon_new();
        btnModifyUser = new newscomponents.RSButtonGradientIcon_new();
        txtNickname10 = new RSMaterialComponent.RSTextFieldOne();
        idProductoVenta = new RSMaterialComponent.RSTextFieldOne();
        txtNickname2 = new RSMaterialComponent.RSTextFieldOne();
        jLabel6 = new javax.swing.JLabel();
        txtNickname4 = new RSMaterialComponent.RSTextFieldOne();
        jLabel11 = new javax.swing.JLabel();
        rSButtonRound1 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound2 = new rojeru_san.rsbutton.RSButtonRound();
        txtNickname5 = new RSMaterialComponent.RSTextFieldOne();
        jLabel8 = new javax.swing.JLabel();
        txtNickname6 = new RSMaterialComponent.RSTextFieldOne();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNickname9 = new RSMaterialComponent.RSTextFieldOne();
        jLabel14 = new javax.swing.JLabel();
        txtNickname11 = new RSMaterialComponent.RSTextFieldOne();
        jLabel17 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        jLabel10 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(995, 702));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(153, 153, 153)));

        rSPanelMaterialGradient1.setBgShade(new java.awt.Color(51, 102, 255));
        rSPanelMaterialGradient1.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSPanelMaterialGradient1.setShadowBottom(false);
        rSPanelMaterialGradient1.setShadowLeft(false);
        rSPanelMaterialGradient1.setShadowRight(false);
        rSPanelMaterialGradient1.setShadowTop(false);

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo de Ventas");

        javax.swing.GroupLayout rSPanelMaterialGradient1Layout = new javax.swing.GroupLayout(rSPanelMaterialGradient1);
        rSPanelMaterialGradient1.setLayout(rSPanelMaterialGradient1Layout);
        rSPanelMaterialGradient1Layout.setHorizontalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rSPanelMaterialGradient1Layout.setVerticalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));
        pnlSlider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchUser.setForeground(new java.awt.Color(51, 51, 51));
        txtSearchUser.setBorderColor(new java.awt.Color(204, 204, 204));
        txtSearchUser.setColorIcon(new java.awt.Color(51, 51, 51));
        txtSearchUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtSearchUser.setPhColor(new java.awt.Color(102, 102, 102));
        txtSearchUser.setPlaceholder("Buscar");
        pnlSlider.add(txtSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 265, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cod. Cliente");
        pnlSlider.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 220, -1));

        tblUsers.setBackground(new java.awt.Color(255, 255, 255));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código", "Producto", "Precio Unitario", "Subtotal", "IGV", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setBackgoundHover(new java.awt.Color(102, 255, 255));
        tblUsers.setEditingColumn(0);
        tblUsers.setEditingRow(0);
        tblUsers.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tblUsers.setWidthBorderRows(0);
        jScrollPane1.setViewportView(tblUsers);

        pnlSlider.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 297, 946, 290));

        btnNewUser.setBackground(new java.awt.Color(0, 255, 51));
        btnNewUser.setText("Generar Venta");
        btnNewUser.setToolTipText("");
        btnNewUser.setColorPrimario(new java.awt.Color(0, 204, 51));
        btnNewUser.setColorPrimarioHover(new java.awt.Color(0, 255, 0));
        btnNewUser.setColorSecundario(new java.awt.Color(0, 102, 51));
        btnNewUser.setColorSecundarioHover(new java.awt.Color(0, 255, 0));
        btnNewUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        pnlSlider.add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 219, -1));

        btnModifyUser.setBackground(new java.awt.Color(0, 255, 51));
        btnModifyUser.setText("Cancelar");
        btnModifyUser.setToolTipText("");
        btnModifyUser.setColorPrimario(new java.awt.Color(255, 102, 102));
        btnModifyUser.setColorPrimarioHover(new java.awt.Color(255, 0, 0));
        btnModifyUser.setColorSecundario(new java.awt.Color(204, 0, 51));
        btnModifyUser.setColorSecundarioHover(new java.awt.Color(255, 0, 0));
        btnModifyUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        pnlSlider.add(btnModifyUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 212, -1));

        txtNickname10.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname10.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname10.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname10.setOpaque(false);
        txtNickname10.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname10.setPlaceholder("Código de Cliente...");
        txtNickname10.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 29, 220, -1));

        idProductoVenta.setBackground(new java.awt.Color(204, 204, 204));
        idProductoVenta.setForeground(new java.awt.Color(0, 102, 255));
        idProductoVenta.setBorderColor(new java.awt.Color(0, 102, 255));
        idProductoVenta.setMargin(new java.awt.Insets(3, 2, 3, 2));
        idProductoVenta.setOpaque(false);
        idProductoVenta.setPhColor(new java.awt.Color(0, 0, 0));
        idProductoVenta.setPlaceholder("Id Producto");
        idProductoVenta.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(idProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        txtNickname2.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname2.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname2.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname2.setOpaque(false);
        txtNickname2.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname2.setPlaceholder("Código Producto...");
        txtNickname2.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 106, 217, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cod. Producto");
        pnlSlider.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 83, 217, -1));

        txtNickname4.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname4.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname4.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname4.setOpaque(false);
        txtNickname4.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname4.setPlaceholder("Precio...");
        txtNickname4.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Precio");
        pnlSlider.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, -1));

        rSButtonRound1.setText("Buscar");
        pnlSlider.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 90, -1));

        rSButtonRound2.setText("Buscar");
        pnlSlider.add(rSButtonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 90, -1));

        txtNickname5.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname5.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname5.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname5.setOpaque(false);
        txtNickname5.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname5.setPlaceholder("Cliente...");
        txtNickname5.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("N° de Serie");
        pnlSlider.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 220, -1));

        txtNickname6.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname6.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname6.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname6.setOpaque(false);
        txtNickname6.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname6.setPlaceholder("Producto...");
        txtNickname6.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Producto");
        pnlSlider.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 87, 350, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Stock");
        pnlSlider.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 110, -1));

        txtNickname9.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname9.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname9.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname9.setOpaque(false);
        txtNickname9.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname9.setPlaceholder("Vendedor...");
        txtNickname9.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 710, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Vendedor");
        pnlSlider.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 470, -1));

        txtNickname11.setForeground(new java.awt.Color(0, 102, 255));
        txtNickname11.setBorderColor(new java.awt.Color(0, 102, 255));
        txtNickname11.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtNickname11.setOpaque(false);
        txtNickname11.setPhColor(new java.awt.Color(0, 0, 153));
        txtNickname11.setPlaceholder("Código...");
        txtNickname11.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtNickname11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 110, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Cantidad");
        pnlSlider.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 110, -1));
        pnlSlider.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 110, 40));
        pnlSlider.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 230, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cliente");
        pnlSlider.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 270, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonGradientIcon_new btnModifyUser;
    public newscomponents.RSButtonGradientIcon_new btnNewUser;
    public RSMaterialComponent.RSTextFieldOne idProductoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private newscomponents.RSPanelEffect pnlSlider;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound1;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound2;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private RSMaterialComponent.RSPanelMaterialGradient rSPanelMaterialGradient1;
    public rojerusan.RSTableMetro tblUsers;
    public RSMaterialComponent.RSTextFieldOne txtNickname10;
    public RSMaterialComponent.RSTextFieldOne txtNickname11;
    public RSMaterialComponent.RSTextFieldOne txtNickname2;
    public RSMaterialComponent.RSTextFieldOne txtNickname4;
    public RSMaterialComponent.RSTextFieldOne txtNickname5;
    public RSMaterialComponent.RSTextFieldOne txtNickname6;
    public RSMaterialComponent.RSTextFieldOne txtNickname9;
    public RSMaterialComponent.RSTextFieldIconOne txtSearchUser;
    // End of variables declaration//GEN-END:variables
}
