/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Natsu98fx
 */
public class VistaCompras extends javax.swing.JPanel {

    /**
     * Creates new form VistaProductos
     */
    public VistaCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rSPanelMaterialGradient1 = new RSMaterialComponent.RSPanelMaterialGradient();
        jLabel1 = new javax.swing.JLabel();
        pnlSlider = new newscomponents.RSPanelEffect();
        txtSearchUser = new RSMaterialComponent.RSTextFieldIconOne();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new rojerusan.RSTableMetro();
        btnNewUser = new newscomponents.RSButtonGradientIcon_new();
        btnRegisterUser = new newscomponents.RSButtonGradientIcon_new();
        btnModifyUser = new newscomponents.RSButtonGradientIcon_new();
        txtCodigoCompra = new RSMaterialComponent.RSTextFieldOne();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcionProducto_Compra = new RSMaterialComponent.RSTextFieldOne();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioCompra_Compra = new RSMaterialComponent.RSTextFieldOne();
        txtCantidad_Compra = new RSMaterialComponent.RSTextFieldOne();
        PrecioVenta_Compra = new RSMaterialComponent.RSTextFieldOne();
        jLabel9 = new javax.swing.JLabel();
        txtIdProvider = new RSMaterialComponent.RSTextFieldOne();
        btnBuscarProducto_Compras = new rojeru_san.rsbutton.RSButtonRound();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(995, 702));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(153, 153, 153)));

        rSPanelMaterialGradient1.setBgShade(new java.awt.Color(51, 102, 255));
        rSPanelMaterialGradient1.setColorPrimario(new java.awt.Color(0, 102, 255));
        rSPanelMaterialGradient1.setShadowBottom(false);
        rSPanelMaterialGradient1.setShadowLeft(false);
        rSPanelMaterialGradient1.setShadowRight(false);
        rSPanelMaterialGradient1.setShadowTop(false);

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo de Compras");

        javax.swing.GroupLayout rSPanelMaterialGradient1Layout = new javax.swing.GroupLayout(rSPanelMaterialGradient1);
        rSPanelMaterialGradient1.setLayout(rSPanelMaterialGradient1Layout);
        rSPanelMaterialGradient1Layout.setHorizontalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterialGradient1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterialGradient1Layout.setVerticalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));
        pnlSlider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchUser.setForeground(new java.awt.Color(51, 51, 51));
        txtSearchUser.setBorderColor(new java.awt.Color(204, 204, 204));
        txtSearchUser.setColorIcon(new java.awt.Color(51, 51, 51));
        txtSearchUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtSearchUser.setPhColor(new java.awt.Color(102, 102, 102));
        txtSearchUser.setPlaceholder("Buscar");
        pnlSlider.add(txtSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 200, 265, -1));

        tblCompras.setBackground(new java.awt.Color(255, 255, 255));
        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código", "Descripción", "Cantidad", "Subtotal", "IGV", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompras.setBackgoundHover(new java.awt.Color(102, 255, 255));
        tblCompras.setEditingColumn(0);
        tblCompras.setEditingRow(0);
        tblCompras.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tblCompras.setWidthBorderRows(0);
        jScrollPane1.setViewportView(tblCompras);

        pnlSlider.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 254, 962, 298));

        btnNewUser.setBackground(new java.awt.Color(0, 255, 51));
        btnNewUser.setText("Nuevo");
        btnNewUser.setToolTipText("");
        btnNewUser.setColorPrimario(new java.awt.Color(0, 204, 51));
        btnNewUser.setColorPrimarioHover(new java.awt.Color(0, 255, 0));
        btnNewUser.setColorSecundario(new java.awt.Color(0, 102, 51));
        btnNewUser.setColorSecundarioHover(new java.awt.Color(0, 255, 0));
        btnNewUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        pnlSlider.add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 570, 219, -1));

        btnRegisterUser.setBackground(new java.awt.Color(75, 172, 198));
        btnRegisterUser.setText("Registrar");
        btnRegisterUser.setToolTipText("");
        btnRegisterUser.setColorPrimario(new java.awt.Color(75, 172, 198));
        btnRegisterUser.setColorPrimarioHover(new java.awt.Color(0, 255, 255));
        btnRegisterUser.setColorSecundario(new java.awt.Color(75, 85, 215));
        btnRegisterUser.setColorSecundarioHover(new java.awt.Color(0, 255, 255));
        btnRegisterUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEND);
        pnlSlider.add(btnRegisterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 570, 212, -1));

        btnModifyUser.setBackground(new java.awt.Color(0, 255, 51));
        btnModifyUser.setText("Modificar");
        btnModifyUser.setToolTipText("");
        btnModifyUser.setColorPrimario(new java.awt.Color(255, 102, 102));
        btnModifyUser.setColorPrimarioHover(new java.awt.Color(255, 0, 0));
        btnModifyUser.setColorSecundario(new java.awt.Color(204, 0, 51));
        btnModifyUser.setColorSecundarioHover(new java.awt.Color(255, 0, 0));
        btnModifyUser.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        pnlSlider.add(btnModifyUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 570, 212, -1));

        txtCodigoCompra.setForeground(new java.awt.Color(0, 102, 255));
        txtCodigoCompra.setBorderColor(new java.awt.Color(0, 102, 255));
        txtCodigoCompra.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtCodigoCompra.setOpaque(false);
        txtCodigoCompra.setPhColor(new java.awt.Color(0, 0, 153));
        txtCodigoCompra.setPlaceholder("Código...");
        txtCodigoCompra.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtCodigoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 29, 217, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Código");
        pnlSlider.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 210, -1));

        txtDescripcionProducto_Compra.setForeground(new java.awt.Color(0, 102, 255));
        txtDescripcionProducto_Compra.setBorderColor(new java.awt.Color(0, 102, 255));
        txtDescripcionProducto_Compra.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtDescripcionProducto_Compra.setOpaque(false);
        txtDescripcionProducto_Compra.setPhColor(new java.awt.Color(0, 0, 153));
        txtDescripcionProducto_Compra.setPlaceholder("Descripción del producto...");
        txtDescripcionProducto_Compra.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtDescripcionProducto_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 29, 610, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripción del Producto");
        pnlSlider.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 6, 610, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad");
        pnlSlider.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Precio Compra");
        pnlSlider.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 223, -1));

        txtPrecioCompra_Compra.setForeground(new java.awt.Color(0, 102, 255));
        txtPrecioCompra_Compra.setBorderColor(new java.awt.Color(0, 102, 255));
        txtPrecioCompra_Compra.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtPrecioCompra_Compra.setOpaque(false);
        txtPrecioCompra_Compra.setPhColor(new java.awt.Color(0, 0, 153));
        txtPrecioCompra_Compra.setPlaceholder("");
        txtPrecioCompra_Compra.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtPrecioCompra_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 220, -1));

        txtCantidad_Compra.setForeground(new java.awt.Color(0, 102, 255));
        txtCantidad_Compra.setBorderColor(new java.awt.Color(0, 102, 255));
        txtCantidad_Compra.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtCantidad_Compra.setOpaque(false);
        txtCantidad_Compra.setPhColor(new java.awt.Color(0, 0, 153));
        txtCantidad_Compra.setPlaceholder("");
        txtCantidad_Compra.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtCantidad_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        PrecioVenta_Compra.setForeground(new java.awt.Color(0, 102, 255));
        PrecioVenta_Compra.setBorderColor(new java.awt.Color(0, 102, 255));
        PrecioVenta_Compra.setMargin(new java.awt.Insets(3, 2, 3, 2));
        PrecioVenta_Compra.setOpaque(false);
        PrecioVenta_Compra.setPhColor(new java.awt.Color(0, 0, 153));
        PrecioVenta_Compra.setPlaceholder("");
        PrecioVenta_Compra.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(PrecioVenta_Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 238, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio Venta");
        pnlSlider.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 232, -1));

        txtIdProvider.setBackground(new java.awt.Color(204, 204, 204));
        txtIdProvider.setForeground(new java.awt.Color(0, 102, 255));
        txtIdProvider.setBorderColor(new java.awt.Color(0, 102, 255));
        txtIdProvider.setMargin(new java.awt.Insets(3, 2, 3, 2));
        txtIdProvider.setOpaque(false);
        txtIdProvider.setPhColor(new java.awt.Color(0, 0, 0));
        txtIdProvider.setPlaceholder("Id Producto");
        txtIdProvider.setSelectionColor(new java.awt.Color(51, 51, 51));
        pnlSlider.add(txtIdProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 200, -1, -1));

        btnBuscarProducto_Compras.setText("Buscar");
        pnlSlider.add(btnBuscarProducto_Compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 90, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSTextFieldOne PrecioVenta_Compra;
    private rojeru_san.rsbutton.RSButtonRound btnBuscarProducto_Compras;
    public newscomponents.RSButtonGradientIcon_new btnModifyUser;
    public newscomponents.RSButtonGradientIcon_new btnNewUser;
    public newscomponents.RSButtonGradientIcon_new btnRegisterUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private newscomponents.RSPanelEffect pnlSlider;
    private RSMaterialComponent.RSPanelMaterialGradient rSPanelMaterialGradient1;
    public rojerusan.RSTableMetro tblCompras;
    public RSMaterialComponent.RSTextFieldOne txtCantidad_Compra;
    public RSMaterialComponent.RSTextFieldOne txtCodigoCompra;
    public RSMaterialComponent.RSTextFieldOne txtDescripcionProducto_Compra;
    public RSMaterialComponent.RSTextFieldOne txtIdProvider;
    public RSMaterialComponent.RSTextFieldOne txtPrecioCompra_Compra;
    public RSMaterialComponent.RSTextFieldIconOne txtSearchUser;
    // End of variables declaration//GEN-END:variables
}
